#!/bin/bash

NAME=cap.png

while true
do
    adb shell /system/bin/screencap -p /sdcard/$NAME
    adb pull /sdcard/$NAME ~/Pictures/
    TIME=$(date +%Y%m%d-%H:%M:%S)

    echo -e "\033[31mTime:${TIME} \033[0m"
    if [ $? -eq 0 ]
        then
        echo -e "\033[32mSuccessfully!\tPath: ~/Pictures/${NAME} \033[0m"
        else
        echo -e "\033[31mFailed \033[0m"
    fi
done
